apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: superapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /meow
        backend:
          serviceName: superapp-svc
          servicePort: 80
